In [2]:
import numpy as np
import pandas as pd

# Creating Arrays from Python Lists
## - np.array()
## - .shape

In [ ]:
# Turn Python list in to Numpy array
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [ ]:
# Nested list result 5 x 5 Matrix
np.array([range(i,i + 5) for i in [1,2,3,4,5]])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [7]:
# Nested list result 10 x 10 Matrix
np.array([range(i,i+10) for i in range(1,11)])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
# Count the shape (rows , columns)
np.array([range(i,i+10) for i in range(1,11)]).shape

(10, 10)

# Creating Arrays from Scratch


In [ ]:
# Create a 10 x 10 matrix integer array filled with zeros
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# Create a 10 x 10 matrix of integer filled with ones
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# Create a 2 X 3 Matrix of interger filled with 2.5
np.full((2,3),2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [ ]:
# Create a 3 x 3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create a array by setting the linear sequence. np.arange(start, stop, increment)
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Create a array of 11 values evenly spaced between 0 to 100. np.linspace(start, stop, frequency)
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# Create a array of random values between 0 and 1
np.random.random((3,3))

array([[0.13362636, 0.27108891, 0.74770029],
       [0.16771344, 0.49432808, 0.78599103],
       [0.39980441, 0.6039195 , 0.33456553]])

In [ ]:
# Create a array of normally distributed random values. np.random.normal(mean, std, matrix)
np.random.normal(3,5,(3,3))

array([[-4.58564874,  2.98918938, -0.59630967],
       [-1.15923596,  4.96918958,  4.40227025],
       [-3.27535632,  1.83459989,  3.14131291]])

In [ ]:
# Create a array of randome int. np.random.randint(a, b ,(i,j)) number between a and b in i x j matrix
np.random.randint(0,10,(3,3))

array([[9, 9, 9],
       [5, 5, 6],
       [2, 9, 9]])

array([0.39645431, 0.19261275, 0.922218  , 0.93674153, 0.63191346,
       0.05833862, 0.02102356, 0.35750661, 0.41978385, 0.41274636,
       0.07198377, 0.1223574 , 0.97971514, 0.16486512, 0.9253474 ])